# .github/pr-labeler.yml
# The bot always updates the labels, add/remove as necessary [default: false]
alwaysReplace: true
# Treats the text and labels as case sensitive [default: true]
caseSensitive: true
# Array of labels to be applied to the PR [default: []]
# Finds the `text` within the PR title and body and applies the `label`
customLabels:
  - text: '- [x] Feature'
    label: 'feature'
  - text: '- [x] Bug Fix'
    label: 'bug'
  - text: '- [x] Tests'
    label: 'test'
  - text: 'WIP: '
    label: 'wip'
# Search the body of the PR for the `text` [default: true]
searchBody: true
# Search the title of the PR for the `text` [default: true]
searchTitle: true
