# .github/pr-labeler.yml
# Treats the text and labels as case sensitive [default: true]
caseSensitive: true
# Array of labels to be applied to the PR [default: []]
# Finds the `text` within the PR title and body and applies the `label`
customLabels:
  - text: '- [x] Feature'
    label: 'feature'
  - text: '- [x] Bug Fix'
    label: 'bug'
  - text: '- [x] Tests'
    label: 'test'
